name: pamride
description: a point scanner app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  #connectivity: 
  google_fonts:
  provider: ^6.0.1
  get: ^4.6.1
  transition: ^2.0.2
  intl: any
  octo_image: ^1.0.0+1
  flutter_svg: ^1.1.6 
  firebase_core: 
  firebase_messaging: 
  responsive_builder: ^0.4.1
  responsive_framework: ^0.2.0
  flutter_rating_bar: ^4.0.0
  adaptive_dialog: ^1.2.0
  flutter_form_builder: 
  #form_builder_extra_fields: ^7.0.0
  form_builder_validators: 
  shimmer: ^2.0.0
  simple_fontellico_progress_dialog: ^0.2.1
  cool_alert: ^1.1.0
  ferry:
  gql_http_link: 
  ferry_flutter:
  ferry_hive_store:
  hive_flutter:
  carousel_slider: ^4.0.0-nullsafety.0
  easy_dynamic_theme: ^2.0.0
  drop_down_list: ^0.0.2
  enhanced_drop_down: ^0.1.7+1
  #date_time_picker: any
  lottie: ^1.4.3
  http: ^0.13.4
  loading_indicator: ^3.0.3
  fluttertoast: ^8.0.9
  file_picker: ^4.6.1
  shared_preferences: ^2.0.15
  permission_handler: ^10.0.0
  open_file: ^3.2.1
  image_picker: ^1.0.0
  gql_websocket_link:
  graphql_flutter: ^5.1.2
  page_transition: ^2.0.9
  geocoder2: ^1.3.0
  geolocator: ^9.0.1
  waterfall_flow: ^3.0.2
  flutter_staggered_grid_view: ^0.6.2
  super_banners: ^0.0.1
  path_provider: ^2.0.11
  font_awesome_flutter: ^10.1.0
  google_maps_flutter: ^2.2.1
  google_api_headers: ^1.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.1
  google_distance_matrix: ^0.0.1
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.6
  date_format: ^2.0.7
  webview_flutter: ^3.0.4
  flutter_screenutil: ^5.6.0
  gql_build: ^0.6.0
  geocode: 1.0.2
  #pagination: ^0.1.0
  url_launcher: ^6.1.7
  in_app_update: 
  flutter_dotenv: ^5.0.2
  flutter_svprogresshud: ^1.0.0
  quickalert:
  cached_network_image: ^3.2.3
  scroll_loop_auto_scroll: ^0.0.5
  uuid: ^3.0.4
  share_plus: 
  algolia_helper_flutter: ^0.2.0
  infinite_scroll_pagination: ^3.2.0   
  firebase_analytics: ^10.4.3 
  pdf: ^3.6.0
  firebase_crashlytics: ^3.3.4 
  image_picker_android: 0.8.5+3
  firebase_performance: ^0.9.2+4
  upgrader: 
  dots_indicator: 
  qr_code_scanner:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  ferry_generator: ^0.6.1
  build_runner:
flutter:
  uses-material-design: true
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
        - asset: fonts/Helvetica-Bold-Font.ttf
          weight: 700
        - asset: fonts/Helvetica-Light.ttf
          weight: 100
    - family: Montserrat
      fonts:
            - asset: fonts/Montserrat-Regular.ttf
    - family: Electrolize
      fonts:
            - asset: fonts/Electrolize-Regular.ttf

  assets:
    - assets/images/
    - assets/
    - assets/assets/
    - .env